version: '3.8'

services:
  spider:
    build:
      context: .
      dockerfile: .ops/docker/go/Dockerfile
    container_name: spider
    volumes:
      - .:/app
    networks:
      - grid
    depends_on:
      - selenium-hub
      - mongodb
      - chromium
      - firefox
    platform: linux/amd64
    environment:
      URLS_FILEPATH: "/public/data/urls.csv"
      FREQUENCY: "1h"

#  selenium:
##    image: seleniarm/standalone-docker:latest
#    image: seleniarm/hub:4.6.0-20221104
#    container_name: selenium
#    shm_size: 4g
#    ports:
#      - "4442-4444:4442-4444"
#    volumes:
#      - selenium-data:/home/seluser
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - grid
#    environment:
#      - SE_NODE_MAX_SESSIONS=5
#      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
#      - SE_NODE_SESSION_TIMEOUT=3350
#      - SE_SESSION_RETRY_INTERVAL=3

  mongodb:
    image: bitnami/mongodb:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - grid
    environment:
      MONGODB_ROOT_USER: "useo"
      MONGODB_ROOT_PASSWORD: "pseo"
      MONGODB_USERNAME: "seo"
      MONGODB_PASSWORD: "seo"
      MONGODB_DATABASE: "seo"

  selenium-hub:
    image: selenium/hub:4.6.0-20221104
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid
    healthcheck:
      test: /opt/bin/check-grid.sh --host 0.0.0.0 --port 4444
      interval: 15s
      timeout: 30s
      retries: 5

  chromium:
    image: seleniarm/node-chromium:4.6.0-20221104
    container_name: selenium-node-chrome
    shm_size: 2g
    networks:
      - grid
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: seleniarm/node-firefox:4.6.0-20221104
    container_name: selenium-node-firefox
    shm_size: 2g
    networks:
      - grid
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

volumes:
  mongo-data:
  selenium-data:

networks:
  grid: