version: '3.8'

services:
  scanner:
    build:
      context: .
      dockerfile: .ops/docker/go/Dockerfile
    volumes:
      - .:/go/src/app
    depends_on:
      - selenium
    command: ["sh", "-c", "go run -tags musl -race ./cmd/main.go"]

  selenium:
    build:
      context: .
      dockerfile: .ops/docker/selenium/Dockerfile
    ports:
      - "4444:4444"
