version: '3.8'

services:
  scanner:
    build:
      context: .
      dockerfile: .ops/docker/go/Dockerfile
    depends_on:
      - selenium
      - mongodb
    platform: linux/amd64
#    command: ["sh", "-c", "go build -o scanner ./cmd/main.go && ./scanner"]
    command: ["sh", "-c", "go run ./cmd/main.go"]

  selenium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2g
    ports:
      - "4444:4444"
    platform: linux/arm64
    volumes:
      - selenium-data:/home/seluser
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: seo
      MONGO_INITDB_ROOT_PASSWORD: seo

volumes:
  mongo-data:
  selenium-data: