version: '3.8'

services:
  scanner:
    build:
      context: .
      dockerfile: .ops/docker/go/Dockerfile
    volumes:
      - .:/go/src/app
    depends_on:
      - selenium
    platform: linux/amd64
    command: ["go", "run", "./cmd/main.go"]

  selenium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2g
    ports:
      - "4444:4444"
    platform: linux/arm64