version: '3.8'

services:
  spider_app:
    build:
      context: .
      dockerfile: .ops/docker/go/dev/Dockerfile
    container_name: spider_app
    volumes:
      - .:/app
    depends_on:
      - mongo_db
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      # Logger
      LOGGER_LEVEL: "debug"
      LOGGER_OUTPUT: "stderr"
      LOGGER_FORMAT: "json"
      LOGGER_CONTEXT_EXTRA_FIELD: "jobId,taskId"
      # Mongodb
      MONGO_HOST: "mongo_db"
      MONGO_PORT: "27017"
      MONGO_LOGIN: "spider"
      MONGO_PASSWORD: "spider"
      MONGO_DATABASE: "spider"
      MONGO_REQUEST_TIMEOUT: "5s"
      # Spider
      URLS_FILEPATH: "/public/data/urls_test.csv"
      JOB_FREQUENCY: "1m"
      TASKS_PER_SECOND_LIMIT: "10"
      TASKS_CONCURRENCY_LIMIT: "10"
      TIMEOUT_PER_URL: "1m"
      USER_AGENTS: "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.5993.70 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
      REQUEST_RETRIES: "3"
      MONGO_PAGES_COLLECTION: "pages"
      # Golang
      GOMAXPROCS: "0"
      # Infra. server
      INFRASTRUCTURE_SERVER_NAME: "infrastructure"
      INFRASTRUCTURE_SERVER_PORT: ":8000"
      INFRASTRUCTURE_SERVER_SHUTDOWN_TIMEOUT: "5s"
      INFRASTRUCTURE_SERVER_REQUEST_TIMEOUT: "1m"

  mongo_db:
    image: bitnami/mongodb:7.0.5
    container_name: mongo_db
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGODB_ROOT_USER: "root_spider"
      MONGODB_ROOT_PASSWORD: "root_spider"
      MONGODB_USERNAME: "spider"
      MONGODB_PASSWORD: "spider"
      MONGODB_DATABASE: "spider"

volumes:
  mongo-data: