version: '3.8'

services:
  spider:
    build:
      context: .
      dockerfile: .ops/docker/go/Dockerfile
    container_name: spider
    volumes:
      - .:/app
    depends_on:
      - selenium
      - mongodb
    platform: linux/amd64
    environment:
      URLS_FILEPATH: "/public/data/urls.csv"
      FREQUENCY: "1h"

  selenium:
    image: seleniarm/standalone-chromium:124.0-chromedriver-124.0-20240427
    container_name: selenium
    shm_size: 2g
    ports:
      - "4444:4444"
    platform: linux/arm64
    volumes:
      - selenium-data:/home/seluser
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  mongodb:
    image: bitnami/mongodb:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGODB_ROOT_USER: "useo"
      MONGODB_ROOT_PASSWORD: "pseo"
      MONGODB_USERNAME: "seo"
      MONGODB_PASSWORD: "seo"
      MONGODB_DATABASE: "seo"

volumes:
  mongo-data:
  selenium-data: