version: '3.8'

services:
  spider:
    build:
      context: .
      dockerfile: .ops/docker/go/Dockerfile
    container_name: spider
    volumes:
      - .:/app
    depends_on:
      - mongodb
    platform: linux/amd64

  mongodb:
    image: bitnami/mongodb:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGODB_ROOT_USER: "useo"
      MONGODB_ROOT_PASSWORD: "pseo"
      MONGODB_USERNAME: "seo"
      MONGODB_PASSWORD: "seo"
      MONGODB_DATABASE: "seo"

volumes:
  mongo-data:
  playwright: